# Generated by Django 5.1.5 on 2025-02-07 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_notification_remove_chatsession_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('button', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TextDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('textarea', models.TextField()),
                ('reference_button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_details', to='chat.buttondetails')),
            ],
        ),
    ]
