# Generated by Django 5.1.6 on 2025-02-10 10:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_buttondetails_textdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textdetails',
            name='textarea',
        ),
        migrations.AddField(
            model_name='textdetails',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Text'),
        ),
    ]
