# Generated by Django 5.1.6 on 2025-02-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroom_update_message_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom_update',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatroom_update',
            name='room_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
