# Generated by Django 5.1.6 on 2025-02-11 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatroom_update_status_alter_chatroom_update_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_update',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom_update'),
        ),
    ]
