# Generated by Django 5.1.6 on 2025-02-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_update_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom_update',
            name='employee_joined',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
