# Generated by Django 5.1.6 on 2025-02-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chatroom_update_employee_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom_update',
            name='employee_joined',
            field=models.CharField(max_length=255),
        ),
    ]
