# Generated by Django 5.1.6 on 2025-02-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatfile',
            name='sender',
            field=models.CharField(max_length=10),
        ),
    ]
