# Generated by Django 5.1.6 on 2025-02-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_chatfile_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom_update',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
